CREATE DATABASE RACHELRDB;
USE RACHELRDB;

CREATE TABLE CUSTOMER(
CUSTOMER_ID VARCHAR(20) NOT NULL,
CUSTOMER_NAME VARCHAR(25) NOT NULL,
USERNAME VARCHAR(25) NOT NULL,
PHONE_NO INT,
WALLET_BALANCE INT,
ADDRESS VARCHAR(30),
CONSTRAINT C_UK  unique key(USERNAME)
);

CREATE TABLE VENDOR(
VENDOR_ID VARCHAR(20) NOT NULL,
VENDOR_NAME VARCHAR(25)NOT NULL,
USERNAME VARCHAR(25)NOT NULL,
PASSWORD VARCHAR(20)NOT NULL,
PHONE_NO INT,
ADDRESS VARCHAR(30),
CONSTRAINT C_FK foreign key(USERNAME) REFERENCES CUSTOMER(USERNAME)
);

CREATE TABLE MENU(
FOOD_ID VARCHAR(20)NOT NULL,
FOOD_ITEM VARCHAR(20) NOT NULL,
AMOUNT INT NOT NULL
);

CREATE TABLE ORDER_(
ORDER_ID VARCHAR(20)NOT NULL,
QUANTITY INT NOT NULL,
DATE DATE,
ESTIMATED_TIME DATETIME,
TOTAL_AMOUNT INT NOT NULL,
ORDER_STATUS VARCHAR(20),
REASON VARCHAR(20)
);