version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: docker-mysql
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - java-mysql 
    environment:
      MYSQL_ROOT_USER: root #root user
      MYSQL_ROOT_PASSWORD: password #root password
    ports:
      - 3306:3306
  app:
    depends_on:
      - mysql
    networks:
      - java-mysql 
    build: .

volumes:
  dbdata: 

networks:
  java-mysql: