name: Docker Images CLI

on:
  push:
    branches: [ "master" ]
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
          # setup Docker buld action
      - 
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: S{{ secrets.DOCKERHUB_TOKEN }}
      -
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: siddheshjungade/demojava-app:1.0