name: learn-github-action
on:
  release:
    type: [push]
jobs:
  build:
    runs-on: ubuntu-letest
    steps:
    - uses: action/checkout@v3
    - name: setup JDK 18
    - uses: actions/setup-java@v3
    - with:
        java-version: "11"
        distribution: "temurin"
        server-id: github 
        settings-path: ${{ github.workspace }}
    - name: Build with Maven
      run: mvn package